var express = require('express');
var router = express.Router();

/* GET users listing. */
router.get('/strings', function(req, res, next) {
  res.send({
    users: ['Abbott, Tomas',
        'Acevedo, Oscar',
        'Acosta, Adam',
        'Adams, Sharon',
        'Adkins, Sharon',
        'Aguilar, Ray',
        'Aguirre, Edward',
        'Albert, Tomas',
        'Alexander, Ray',
        'Alford, David',
        'Allen, Nancy',
        'Allison, Nancy',
        'Alston, Nancy',
        'Alvarado, Oscar',
        'Alvarez, Zorb',
        'Anderson, Nancy',
        'Andrews, Sharon',
        'Anthony, Kelly',
        'Armstrong, Gary',
        'Arnold, David',
        'Ashley, Kelly',
        'Atkins, Sharon',
        'Atkinson, Nancy',
        'Austin, Nancy',
        'Avery, Kelly',
        'Avila, Adam',
        'Ayala, Adam',
        'Ayers, Sharon',
        'Bailey, Kelly',
        'Baird, David',
        'Baker, Ray',
        'Baldwin, Nancy',
        'Ball, Larry',
        'Ballard, David',
        'Banks, Sharon',
        'Barber, Ray',
        'Barker, Ray',
        'Barlow, Wilson',
        'Barnes, Sharon',
        'Barnett, Tomas',
        'Barr, Ray',
        'Barrera, Adam',
        'Barrett, Tomas',
        'Barron, Nancy',
        'Barry, Kelly',
        'Bartlett, Tomas',
        'Barton, Nancy',
        'Bass, Sharon',
        'Bates, Sharon',
        'Battle, Edward',
        'Bauer, Ray',
        'Baxter, Ray',
        'Beach, Helen',
        'Bean, Nancy',
        'Beard, David',
        'Beasley, Kelly',
        'Beck, Krishna',
        'Becker, Ray',
        'Bell, Larry',
        'Bender, Ray',
        'Benjamin, Nancy',
        'Bennett, Tomas',
        'Benson, Nancy',
        'Bentley, Kelly',
        'Benton, Nancy',
        'Berg, Gary',
        'Berger, Ray',
        'Bernard, David',
        'Berry, Kelly',
        'Best, Tomas',
        'Bird, David',
        'Bishop, Paul',
        'Black, Krishna',
        'Blackburn, Nancy',
        'Blackwell, Larry',
        'Blair, Ray',
        'Blake, Edward',
        'Blanchard, David',
        'Blankenship, Paul',
        'Blevins, Sharon',
        'Bolton, Nancy',
        'Bond, David',
        'Bonner, Ray',
        'Booker, Ray',
        'Boone, Edward',
        'Booth, Helen',
        'Bowen, Nancy',
        'Bowers, Sharon',
        'Bowman, Nancy',
        'Boyd, David',
        'Boyer, Ray',
        'Boyle, Edward',
        'Bradford, David',
        'Bradley, Kelly',
        'Bradshaw, Wilson',
        'Brady, Kelly',
        'Branch, Helen',
        'Bray, Kelly',
        'Brennan, Nancy',
        'Brewer, Ray',
        'Bridges, Sharon',
        'Briggs, Sharon',
        'Bright, Tomas',
        'Britt, Tomas',
        'Brock, Krishna',
        'Brooks, Sharon',
        'Brown, Nancy',
        'Browning, Gary',
        'Bruce, Edward',
        'Bryan, Nancy',
        'Bryant, Tomas',
        'Buchanan, Nancy',
        'Buck, Krishna',
        'Buckley, Kelly',
        'Buckner, Ray',
        'Bullock, Krishna',
        'Burch, Helen',
        'Burgess, Sharon',
        'Burke, Edward',
        'Burks, Sharon',
        'Burnett, Tomas',
        'Burns, Sharon',
        'Burris, Sharon',
        'Burt, Tomas',
        'Burton, Nancy',
        'Bush, Helen',
        'Butler, Ray',
        'Byers, Sharon',
        'Byrd, David',
        'Cabrera, Adam',
        'Cain, Nancy',
        'Calderon, Nancy',
        'Caldwell, Larry',
        'Calhoun, Nancy',
        'Callahan, Nancy',
        'Camacho, Oscar',
        'Cameron, Nancy',
        'Campbell, Larry',
        'Campos, Sharon',
        'Cannon, Nancy',
        'Cantrell, Larry',
        'Cantu, Ubuntu',
        'Cardenas, Sharon',
        'Carey, Kelly',
        'Carlson, Nancy',
        'Carney, Kelly',
        'Carpenter, Ray',
        'Carr, Ray',
        'Carrillo, Oscar',
        'Carroll, Larry',
        'Carson, Nancy',
        'Carter, Ray',
        'Carver, Ray',
        'Case, Edward',
        'Casey, Kelly',
        'Cash, Helen',
        'Castaneda, Adam',
        'Castillo, Oscar',
        'Castro, Oscar',
        'Cervantes, Sharon',
        'Chambers, Sharon',
        'Chan, Nancy',
        'Chandler, Ray',
        'Chaney, Kelly',
        'Chang, Gary',
        'Chapman, Nancy',
        'Charles, Sharon',
        'Chase, Edward',
        'Chavez, Zorb',
        'Chen, Nancy',
        'Cherry, Kelly',
        'Christensen, Nancy',
        'Christian, Nancy',
        'Church, Helen',
        'Clark, Krishna',
        'Clarke, Edward',
        'Clay, Kelly',
        'Clayton, Nancy',
        'Clements, Sharon',
        'Clemons, Sharon',
        'Cleveland, David',
        'Cline, Edward',
        'Cobb, Barry',
        'Cochran, Nancy',
        'Coffey, Kelly',
        'Cohen, Nancy',
        'Cole, Edward',
        'Coleman, Nancy',
        'Collier, Ray',
        'Collins, Sharon',
        'Colon, Nancy',
        'Combs, Sharon',
        'Compton, Nancy',
        'Conley, Kelly',
        'Conner, Ray',
        'Conrad, David',
        'Contreras, Sharon',
        'Conway, Kelly',
        'Cook, Krishna',
        'Cooke, Edward',
        'Cooley, Kelly',
        'Cooper, Ray',
        'Copeland, David',
        'Cortez, Zorb',
        'Cote, Edward',
        'Cotton, Nancy',
        'Cox, Xander',
        'Craft, Tomas',
        'Craig, Gary',
        'Crane, Edward',
        'Crawford, David',
        'Crosby, Kelly',
        'Cross, Sharon',
        'Cruz, Zorb',
        'Cummings, Sharon',
        'Cunningham, Michael',
        'Curry, Kelly',
        'Curtis, Sharon',
        'Dale, Edward',
        'Dalton, Nancy',
        'Daniel, Larry',
        'Daniels, Sharon',
        'Daugherty, Kelly',
        'Davenport, Tomas',
        'David, David',
        'Davidson, Nancy',
        'Davis, Sharon',
        'Dawson, Nancy',
        'Day, Kelly',
        'Dean, Nancy',
        'Decker, Ray',
        'Dejesus, Sharon',
        'Delacruz, Zorb',
        'Delaney, Kelly',
        'Deleon, Nancy',
        'Delgado, Oscar',
        'Dennis, Sharon',
        'Diaz, Zorb',
        'Dickerson, Nancy',
        'Dickson, Nancy',
        'Dillard, David',
        'Dillon, Nancy',
        'Dixon, Nancy',
        'Dodson, Nancy',
        'Dominguez, Zorb',
        'Donaldson, Nancy',
        'Donovan, Nancy',
        'Dorsey, Kelly',
        'Dotson, Nancy',
        'Douglas, Sharon',
        'Downs, Sharon',
        'Doyle, Edward',
        'Drake, Edward',
        'Dudley, Kelly',
        'Duffy, Kelly',
        'Duke, Edward',
        'Duncan, Nancy',
        'Dunlap, Paul',
        'Dunn, Nancy',
        'Duran, Nancy',
        'Durham, Michael',
        'Dyer, Ray',
        'Eaton, Nancy',
        'Edwards, Sharon',
        'Elliott, Tomas',
        'Ellis, Sharon',
        'Ellison, Nancy',
        'Emerson, Nancy',
        'England, David',
        'English, Helen',
        'Erickson, Nancy',
        'Espinoza, Adam',
        'Estes, Sharon',
        'Estrada, Adam',
        'Evans, Sharon',
        'Everett, Tomas',
        'Ewing, Gary',
        'Farley, Kelly',
        'Farmer, Ray',
        'Farrell, Larry',
        'Faulkner, Ray',
        'Ferguson, Nancy',
        'Fernandez, Zorb',
        'Ferrell, Larry',
        'Fields, Sharon',
        'Figueroa, Adam',
        'Finch, Helen',
        'Finley, Kelly',
        'Fischer, Ray',
        'Fisher, Ray',
        'Fitzgerald, David',
        'Fitzpatrick, Krishna',
        'Fleming, Gary',
        'Fletcher, Ray',
        'Flores, Sharon',
        'Flowers, Sharon',
        'Floyd, David',
        'Flynn, Nancy',
        'Foley, Kelly',
        'Forbes, Sharon',
        'Ford, David',
        'Foreman, Nancy',
        'Foster, Ray',
        'Fowler, Ray',
        'Fox, Xander',
        'Francis, Sharon',
        'Franco, Oscar',
        'Frank, Krishna',
        'Franklin, Nancy',
        'Franks, Sharon',
        'Frazier, Ray',
        'Frederick, Krishna',
        'Freeman, Nancy',
        'French, Helen',
        'Frost, Tomas',
        'Fry, Kelly',
        'Frye, Edward',
        'Fuentes, Sharon',
        'Fuller, Ray',
        'Fulton, Nancy',
        'Gaines, Sharon',
        'Gallagher, Ray',
        'Gallegos, Sharon',
        'Galloway, Kelly',
        'Gamble, Edward',
        'Garcia, Adam',
        'Gardner, Ray',
        'Garner, Ray',
        'Garrett, Tomas',
        'Garrison, Nancy',
        'Garza, Adam',
        'Gates, Sharon',
        'Gay, Kelly',
        'Gentry, Kelly',
        'George, Edward',
        'Gibbs, Sharon',
        'Gibson, Nancy',
        'Gilbert, Tomas',
        'Giles, Sharon',
        'Gill, Larry',
        'Gillespie, Edward',
        'Gilliam, Michael',
        'Gilmore, Edward',
        'Glass, Sharon',
        'Glenn, Nancy',
        'Glover, Ray',
        'Goff, Frank',
        'Golden, Nancy',
        'Gomez, Zorb',
        'Gonzales, Sharon',
        'Gonzalez, Zorb',
        'Good, David',
        'Goodman, Nancy',
        'Goodwin, Nancy',
        'Gordon, Nancy',
        'Gould, David',
        'Graham, Michael',
        'Grant, Tomas',
        'Graves, Sharon',
        'Gray, Kelly',
        'Green, Nancy',
        'Greene, Edward',
        'Greer, Ray',
        'Gregory, Kelly',
        'Griffin, Nancy',
        'Griffith, Helen',
        'Grimes, Sharon',
        'Gross, Sharon',
        'Guerra, Adam',
        'Guerrero, Oscar',
        'Guthrie, Edward',
        'Gutierrez, Zorb',
        'Guy, Kelly',
        'Guzman, Nancy',
        'Hahn, Nancy',
        'Hale, Edward',
        'Haley, Kelly',
        'Hall, Larry',
        'Hamilton, Nancy',
        'Hammond, David',
        'Hampton, Nancy',
        'Hancock, Krishna',
        'Haney, Kelly',
        'Hansen, Nancy',
        'Hanson, Nancy',
        'Hardin, Nancy',
        'Harding, Gary',
        'Hardy, Kelly',
        'Harmon, Nancy',
        'Harper, Ray',
        'Harrell, Larry',
        'Harrington, Nancy',
        'Harris, Sharon',
        'Harrison, Nancy',
        'Hart, Tomas',
        'Hartman, Nancy',
        'Harvey, Kelly',
        'Hatfield, David',
        'Hawkins, Sharon',
        'Hayden, Nancy',
        'Hayes, Sharon',
        'Haynes, Sharon',
        'Hays, Sharon',
        'Head, David',
        'Heath, Helen',
        'Hebert, Tomas',
        'Henderson, Nancy',
        'Hendricks, Sharon',
        'Hendrix, Xander',
        'Henry, Kelly',
        'Hensley, Kelly',
        'Henson, Nancy',
        'Herman, Nancy',
        'Hernandez, Zorb',
        'Herrera, Adam',
        'Herring, Gary',
        'Hess, Sharon',
        'Hester, Ray',
        'Hewitt, Tomas',
        'Hickman, Nancy',
        'Hicks, Sharon',
        'Higgins, Sharon',
        'Hill, Larry',
        'Hines, Sharon',
        'Hinton, Nancy',
        'Hobbs, Sharon',
        'Hodge, Edward',
        'Hodges, Sharon',
        'Hoffman, Nancy',
        'Hogan, Nancy',
        'Holcomb, Barry',
        'Holden, Nancy',
        'Holder, Ray',
        'Holland, David',
        'Holloway, Kelly',
        'Holman, Nancy',
        'Holmes, Sharon',
        'Holt, Tomas',
        'Hood, David',
        'Hooper, Ray',
        'Hoover, Ray',
        'Hopkins, Sharon',
        'Hopper, Ray',
        'Horn, Nancy',
        'Horne, Edward',
        'Horton, Nancy',
        'House, Edward',
        'Houston, Nancy',
        'Howard, David',
        'Howe, Edward',
        'Howell, Larry',
        'Hubbard, David',
        'Huber, Ray',
        'Hudson, Nancy',
        'Huff, Frank',
        'Huffman, Nancy',
        'Hughes, Sharon',
        'Hull, Larry',
        'Humphrey, Kelly',
        'Hunt, Tomas',
        'Hunter, Ray',
        'Hurley, Kelly',
        'Hurst, Tomas',
        'Hutchinson, Nancy',
        'Hyde, Edward',
        'Ingram, Michael',
        'Irwin, Nancy',
        'Jackson, Nancy',
        'Jacobs, Sharon',
        'Jacobson, Nancy',
        'James, Sharon',
        'Jarvis, Sharon',
        'Jefferson, Nancy',
        'Jenkins, Sharon',
        'Jennings, Sharon',
        'Jensen, Nancy',
        'Jimenez, Zorb',
        'Johns, Sharon',
        'Johnson, Nancy',
        'Johnston, Nancy',
        'Jones, Sharon',
        'Jordan, Nancy',
        'Joseph, Helen',
        'Joyce, Edward',
        'Joyner, Ray',
        'Juarez, Zorb',
        'Justice, Edward',
        'Kane, Edward',
        'Kaufman, Nancy',
        'Keith, Helen',
        'Keller, Ray',
        'Kelley, Kelly',
        'Kelly, Kelly',
        'Kemp, Paul',
        'Kennedy, Kelly',
        'Kent, Tomas',
        'Kerr, Ray',
        'Key, Kelly',
        'Kidd, David',
        'Kim, Michael',
        'King, Gary',
        'Kinney, Kelly',
        'Kirby, Kelly',
        'Kirk, Krishna',
        'Kirkland, David',
        'Klein, Nancy',
        'Kline, Edward',
        'Knapp, Paul',
        'Knight, Tomas',
        'Knowles, Sharon',
        'Knox, Xander',
        'Koch, Helen',
        'Kramer, Ray',
        'Lamb, Barry',
        'Lambert, Tomas',
        'Lancaster, Ray',
        'Landry, Kelly',
        'Lane, Edward',
        'Lang, Gary',
        'Langley, Kelly',
        'Lara, Adam',
        'Larsen, Nancy',
        'Larson, Nancy',
        'Lawrence, Edward',
        'Lawson, Nancy',
        'Le, Edward',
        'Leach, Helen',
        'Leblanc, Carl',
        'Lee, Edward',
        'Leon, Nancy',
        'Leonard, David',
        'Lester, Ray',
        'Levine, Edward',
        'Levy, Kelly',
        'Lewis, Sharon',
        'Lindsay, Kelly',
        'Lindsey, Kelly',
        'Little, Edward',
        'Livingston, Nancy',
        'Lloyd, David',
        'Logan, Nancy',
        'Long, Gary',
        'Lopez, Zorb',
        'Lott, Tomas',
        'Love, Edward',
        'Lowe, Edward',
        'Lowery, Kelly',
        'Lucas, Sharon',
        'Luna, Adam',
        'Lynch, Helen',
        'Lynn, Nancy',
        'Lyons, Sharon',
        'Macdonald, David',
        'Macias, Sharon',
        'Mack, Krishna',
        'Madden, Nancy',
        'Maddox, Xander',
        'Maldonado, Oscar',
        'Malone, Edward',
        'Mann, Nancy',
        'Manning, Gary',
        'Marks, Sharon',
        'Marquez, Zorb',
        'Marsh, Helen',
        'Marshall, Larry',
        'Martin, Nancy',
        'Martinez, Zorb',
        'Mason, Nancy',
        'Massey, Kelly',
        'Mathews, Sharon',
        'Mathis, Sharon',
        'Matthews, Sharon',
        'Maxwell, Larry',
        'May, Kelly',
        'Mayer, Ray',
        'Maynard, David',
        'Mayo, Oscar',
        'Mays, Sharon',
        'Mcbride, Edward',
        'Mccall, Larry',
        'Mccarthy, Kelly',
        'Mccarty, Kelly',
        'Mcclain, Nancy',
        'Mcclure, Edward',
        'Mcconnell, Larry',
        'Mccormick, Krishna',
        'Mccoy, Kelly',
        'Mccray, Kelly',
        'Mccullough, Helen',
        'Mcdaniel, Larry',
        'Mcdonald, David',
        'Mcdowell, Larry',
        'Mcfadden, Nancy',
        'Mcfarland, David',
        'Mcgee, Edward',
        'Mcgowan, Nancy',
        'Mcguire, Edward',
        'Mcintosh, Helen',
        'Mcintyre, Edward',
        'Mckay, Kelly',
        'Mckee, Edward',
        'Mckenzie, Edward',
        'Mckinney, Kelly',
        'Mcknight, Tomas',
        'Mclaughlin, Nancy',
        'Mclean, Nancy',
        'Mcleod, David',
        'Mcmahon, Nancy',
        'Mcmillan, Nancy',
        'Mcneil, Larry',
        'Mcpherson, Nancy',
        'Meadows, Sharon',
        'Medina, Adam',
        'Mejia, Adam',
        'Melendez, Zorb',
        'Melton, Nancy',
        'Mendez, Zorb',
        'Mendoza, Adam',
        'Mercado, Oscar',
        'Mercer, Ray',
        'Merrill, Larry',
        'Merritt, Tomas',
        'Meyer, Ray',
        'Meyers, Sharon',
        'Michael, Larry',
        'Middleton, Nancy',
        'Miles, Sharon',
        'Miller, Ray',
        'Mills, Sharon',
        'Miranda, Adam',
        'Mitchell, Larry',
        'Molina, Adam',
        'Monroe, Edward',
        'Montgomery, Kelly',
        'Montoya, Adam',
        'Moody, Kelly',
        'Moon, Nancy',
        'Mooney, Kelly',
        'Moore, Edward',
        'Morales, Sharon',
        'Moran, Nancy',
        'Moreno, Oscar',
        'Morgan, Nancy',
        'Morin, Nancy',
        'Morris, Sharon',
        'Morrison, Nancy',
        'Morrow, Wilson',
        'Morse, Edward',
        'Morton, Nancy',
        'Moses, Sharon',
        'Mosley, Kelly',
        'Moss, Sharon',
        'Mueller, Ray',
        'Mullen, Nancy',
        'Mullins, Sharon',
        'Munoz, Zorb',
        'Murphy, Kelly',
        'Murray, Kelly',
        'Myers, Sharon',
        'Nash, Helen',
        'Navarro, Oscar',
        'Neal, Larry',
        'Nelson, Nancy',
        'Newman, Nancy',
        'Newton, Nancy',
        'Nguyen, Nancy',
        'Nichols, Sharon',
        'Nicholson, Nancy',
        'Nielsen, Nancy',
        'Nieves, Sharon',
        'Nixon, Nancy',
        'Noble, Edward',
        'Noel, Larry',
        'Nolan, Nancy',
        'Norman, Nancy',
        'Norris, Sharon',
        'Norton, Nancy',
        'Nunez, Zorb',
        'Obrien, Nancy',
        'Ochoa, Adam',
        'Oconnor, Ray',
        'Odom, Michael',
        'Odonnell, Larry',
        'Oliver, Ray',
        'Olsen, Nancy',
        'Olson, Nancy',
        'Oneal, Larry',
        'Oneil, Larry',
        'Oneill, Larry',
        'Orr, Ray',
        'Ortega, Adam',
        'Ortiz, Zorb',
        'Osborn, Nancy',
        'Osborne, Edward',
        'Owen, Nancy',
        'Owens, Sharon',
        'Pace, Edward',
        'Pacheco, Oscar',
        'Padilla, Adam',
        'Page, Edward',
        'Palmer, Ray',
        'Park, Krishna',
        'Parker, Ray',
        'Parks, Sharon',
        'Parrish, Helen',
        'Parsons, Sharon',
        'Pate, Edward',
        'Patel, Larry',
        'Patrick, Krishna',
        'Patterson, Nancy',
        'Patton, Nancy',
        'Paul, Larry',
        'Payne, Edward',
        'Pearson, Nancy',
        'Peck, Krishna',
        'Pena, Adam',
        'Pennington, Nancy',
        'Perez, Zorb',
        'Perkins, Sharon',
        'Perry, Kelly',
        'Peters, Sharon',
        'Petersen, Nancy',
        'Peterson, Nancy',
        'Petty, Kelly',
        'Phelps, Sharon',
        'Phillips, Sharon',
        'Pickett, Tomas',
        'Pierce, Edward',
        'Pittman, Nancy',
        'Pitts, Sharon',
        'Pollard, David',
        'Poole, Edward',
        'Pope, Edward',
        'Porter, Ray',
        'Potter, Ray',
        'Potts, Sharon',
        'Powell, Larry',
        'Powers, Sharon',
        'Pratt, Tomas',
        'Preston, Nancy',
        'Price, Edward',
        'Prince, Edward',
        'Pruitt, Tomas',
        'Puckett, Tomas',
        'Pugh, Helen',
        'Quinn, Nancy',
        'Ramirez, Zorb',
        'Ramos, Sharon',
        'Ramsey, Kelly',
        'Randall, Larry',
        'Randolph, Helen',
        'Rasmussen, Nancy',
        'Ratliff, Frank',
        'Ray, Kelly',
        'Raymond, David',
        'Reed, David',
        'Reese, Edward',
        'Reeves, Sharon',
        'Reid, David',
        'Reilly, Kelly',
        'Reyes, Sharon',
        'Reynolds, Sharon',
        'Rhodes, Sharon',
        'Rice, Edward',
        'Rich, Helen',
        'Richard, David',
        'Richards, Sharon',
        'Richardson, Nancy',
        'Richmond, David',
        'Riddle, Edward',
        'Riggs, Sharon',
        'Riley, Kelly',
        'Rios, Sharon',
        'Rivas, Sharon',
        'Rivera, Adam',
        'Rivers, Sharon',
        'Roach, Helen',
        'Robbins, Sharon',
        'Roberson, Nancy',
        'Roberts, Sharon',
        'Robertson, Nancy',
        'Robinson, Nancy',
        'Robles, Sharon',
        'Rocha, Adam',
        'Rodgers, Sharon',
        'Rodriguez, Zorb',
        'Rodriquez, Zorb',
        'Rogers, Sharon',
        'Rojas, Sharon',
        'Rollins, Sharon',
        'Roman, Nancy',
        'Romero, Oscar',
        'Rosa, Adam',
        'Rosales, Sharon',
        'Rosario, Oscar',
        'Rose, Edward',
        'Ross, Sharon',
        'Roth, Helen',
        'Rowe, Edward',
        'Rowland, David',
        'Roy, Kelly',
        'Ruiz, Zorb',
        'Rush, Helen',
        'Russell, Larry',
        'Russo, Oscar',
        'Rutledge, Edward',
        'Ryan, Nancy',
        'Salas, Sharon',
        'Salazar, Ray',
        'Salinas, Sharon',
        'Sampson, Nancy',
        'Sanchez, Zorb',
        'Sanders, Sharon',
        'Sandoval, Larry',
        'Sanford, David',
        'Santana, Adam',
        'Santiago, Oscar',
        'Santos, Sharon',
        'Sargent, Tomas',
        'Saunders, Sharon',
        'Savage, Edward',
        'Sawyer, Ray',
        'Schmidt, Tomas',
        'Schneider, Ray',
        'Schroeder, Ray',
        'Schultz, Zorb',
        'Schwartz, Zorb',
        'Scott, Tomas',
        'Sears, Sharon',
        'Sellers, Sharon',
        'Serrano, Oscar',
        'Sexton, Nancy',
        'Shaffer, Ray',
        'Shannon, Nancy',
        'Sharp, Paul',
        'Sharpe, Edward',
        'Shaw, Wilson',
        'Shelton, Nancy',
        'Shepard, David',
        'Shepherd, David',
        'Sheppard, David',
        'Sherman, Nancy',
        'Shields, Sharon',
        'Short, Tomas',
        'Silva, Adam',
        'Simmons, Sharon',
        'Simon, Nancy',
        'Simpson, Nancy',
        'Sims, Sharon',
        'Singleton, Nancy',
        'Skinner, Ray',
        'Slater, Ray',
        'Sloan, Nancy',
        'Small, Larry',
        'Smith, Helen',
        'Snider, Ray',
        'Snow, Wilson',
        'Snyder, Ray',
        'Solis, Sharon',
        'Solomon, Nancy',
        'Sosa, Adam',
        'Soto, Oscar',
        'Sparks, Sharon',
        'Spears, Sharon',
        'Spence, Edward',
        'Spencer, Ray',
        'Stafford, David',
        'Stanley, Kelly',
        'Stanton, Nancy',
        'Stark, Krishna',
        'Steele, Edward',
        'Stein, Nancy',
        'Stephens, Sharon',
        'Stephenson, Nancy',
        'Stevens, Sharon',
        'Stevenson, Nancy',
        'Stewart, Tomas',
        'Stokes, Sharon',
        'Stone, Edward',
        'Stout, Tomas',
        'Strickland, David',
        'Strong, Gary',
        'Stuart, Tomas',
        'Suarez, Zorb',
        'Sullivan, Nancy',
        'Summers, Sharon',
        'Sutton, Nancy',
        'Swanson, Nancy',
        'Sweeney, Kelly',
        'Sweet, Tomas',
        'Sykes, Sharon',
        'Talley, Kelly',
        'Tanner, Ray',
        'Tate, Edward',
        'Taylor, Ray',
        'Terrell, Larry',
        'Terry, Kelly',
        'Thomas, Sharon',
        'Thompson, Nancy',
        'Thornton, Nancy',
        'Tillman, Nancy',
        'Todd, David',
        'Torres, Sharon',
        'Townsend, David',
        'Tran, Nancy',
        'Travis, Sharon',
        'Trevino, Oscar',
        'Trujillo, Oscar',
        'Tucker, Ray',
        'Turner, Ray',
        'Tyler, Ray',
        'Tyson, Nancy',
        'Underwood, David',
        'Valdez, Zorb',
        'Valencia, Adam',
        'Valentine, Edward',
        'Valenzuela, Adam',
        'Vance, Edward',
        'Vang, Gary',
        'Vargas, Sharon',
        'Vasquez, Zorb',
        'Vaughan, Nancy',
        'Vaughn, Nancy',
        'Vazquez, Zorb',
        'Vega, Adam',
        'Velasquez, Zorb',
        'Velazquez, Zorb',
        'Velez, Zorb',
        'Villarreal, Larry',
        'Vincent, Tomas',
        'Vinson, Nancy',
        'Wade, Edward',
        'Wagner, Ray',
        'Walker, Ray',
        'Wall, Larry',
        'Wallace, Edward',
        'Waller, Ray',
        'Walls, Sharon',
        'Walsh, Helen',
        'Walter, Ray',
        'Walters, Sharon',
        'Walton, Nancy',
        'Ward, David',
        'Ware, Edward',
        'Warner, Ray',
        'Warren, Nancy',
        'Washington, Nancy',
        'Waters, Sharon',
        'Watkins, Sharon',
        'Watson, Nancy',
        'Watts, Sharon',
        'Weaver, Ray',
        'Webb, Barry',
        'Weber, Ray',
        'Webster, Ray',
        'Weeks, Sharon',
        'Weiss, Sharon',
        'Welch, Helen',
        'Wells, Sharon',
        'West, Tomas',
        'Wheeler, Ray',
        'Whitaker, Ray',
        'White, Edward',
        'Whitehead, David',
        'Whitfield, David',
        'Whitley, Kelly',
        'Whitney, Kelly',
        'Wiggins, Sharon',
        'Wilcox, Xander',
        'Wilder, Ray',
        'Wiley, Kelly',
        'Wilkerson, Nancy',
        'Wilkins, Sharon',
        'Wilkinson, Nancy',
        'William, Michael',
        'Williams, Sharon',
        'Williamson, Nancy',
        'Willis, Sharon',
        'Wilson, Nancy',
        'Winters, Sharon',
        'Wise, Edward',
        'Witt, Tomas',
        'Wolf, Frank',
        'Wolfe, Edward',
        'Wong, Gary',
        'Wood, David',
        'Woodard, David',
        'Woods, Sharon',
        'Woodward, David',
        'Wooten, Nancy',
        'Workman, Nancy',
        'Wright, Tomas',
        'Wyatt, Tomas',
        'Wynn, Nancy',
        'Yang, Gary',
        'Yates, Sharon',
        'York, Krishna',
        'Young, Gary',
        'Zamora, Adam',
        'Zimmerman, Andy']
  });
});

router.get('/objects', function(req, res, next) {
    res.send({
        users: [{name : 'Abbott, Tomas'},
            {name : 'Acevedo, Oscar'},
            {name : 'Acosta, Adam'},
            {name : 'Adams, Sharon'},
            {name : 'Adkins, Sharon'},
            {name : 'Aguilar, Ray'},
            {name : 'Aguirre, Edward'},
            {name : 'Albert, Tomas'},
            {name : 'Alexander, Ray'},
            {name : 'Alford, David'},
            {name : 'Allen, Nancy'},
            {name : 'Allison, Nancy'},
            {name : 'Alston, Nancy'},
            {name : 'Alvarado, Oscar'},
            {name : 'Alvarez, Zorb'},
            {name : 'Anderson, Nancy'},
            {name : 'Andrews, Sharon'},
            {name : 'Anthony, Kelly'},
            {name : 'Armstrong, Gary'},
            {name : 'Arnold, David'},
            {name : 'Ashley, Kelly'},
            {name : 'Atkins, Sharon'},
            {name : 'Atkinson, Nancy'},
            {name : 'Austin, Nancy'},
            {name : 'Avery, Kelly'},
            {name : 'Avila, Adam'},
            {name : 'Ayala, Adam'},
            {name : 'Ayers, Sharon'},
            {name : 'Bailey, Kelly'},
            {name : 'Baird, David'},
            {name : 'Baker, Ray'},
            {name : 'Baldwin, Nancy'},
            {name : 'Ball, Larry'},
            {name : 'Ballard, David'},
            {name : 'Banks, Sharon'},
            {name : 'Barber, Ray'},
            {name : 'Barker, Ray'},
            {name : 'Barlow, Wilson'},
            {name : 'Barnes, Sharon'},
            {name : 'Barnett, Tomas'},
            {name : 'Barr, Ray'},
            {name : 'Barrera, Adam'},
            {name : 'Barrett, Tomas'},
            {name : 'Barron, Nancy'},
            {name : 'Barry, Kelly'},
            {name : 'Bartlett, Tomas'},
            {name : 'Barton, Nancy'},
            {name : 'Bass, Sharon'},
            {name : 'Bates, Sharon'},
            {name : 'Battle, Edward'},
            {name : 'Bauer, Ray'},
            {name : 'Baxter, Ray'},
            {name : 'Beach, Helen'},
            {name : 'Bean, Nancy'},
            {name : 'Beard, David'},
            {name : 'Beasley, Kelly'},
            {name : 'Beck, Krishna'},
            {name : 'Becker, Ray'},
            {name : 'Bell, Larry'},
            {name : 'Bender, Ray'},
            {name : 'Benjamin, Nancy'},
            {name : 'Bennett, Tomas'},
            {name : 'Benson, Nancy'},
            {name : 'Bentley, Kelly'},
            {name : 'Benton, Nancy'},
            {name : 'Berg, Gary'},
            {name : 'Berger, Ray'},
            {name : 'Bernard, David'},
            {name : 'Berry, Kelly'},
            {name : 'Best, Tomas'},
            {name : 'Bird, David'},
            {name : 'Bishop, Paul'},
            {name : 'Black, Krishna'},
            {name : 'Blackburn, Nancy'},
            {name : 'Blackwell, Larry'},
            {name : 'Blair, Ray'},
            {name : 'Blake, Edward'},
            {name : 'Blanchard, David'},
            {name : 'Blankenship, Paul'},
            {name : 'Blevins, Sharon'},
            {name : 'Bolton, Nancy'},
            {name : 'Bond, David'},
            {name : 'Bonner, Ray'},
            {name : 'Booker, Ray'},
            {name : 'Boone, Edward'},
            {name : 'Booth, Helen'},
            {name : 'Bowen, Nancy'},
            {name : 'Bowers, Sharon'},
            {name : 'Bowman, Nancy'},
            {name : 'Boyd, David'},
            {name : 'Boyer, Ray'},
            {name : 'Boyle, Edward'},
            {name : 'Bradford, David'},
            {name : 'Bradley, Kelly'},
            {name : 'Bradshaw, Wilson'},
            {name : 'Brady, Kelly'},
            {name : 'Branch, Helen'},
            {name : 'Bray, Kelly'},
            {name : 'Brennan, Nancy'},
            {name : 'Brewer, Ray'},
            {name : 'Bridges, Sharon'},
            {name : 'Briggs, Sharon'},
            {name : 'Bright, Tomas'},
            {name : 'Britt, Tomas'},
            {name : 'Brock, Krishna'},
            {name : 'Brooks, Sharon'},
            {name : 'Brown, Nancy'},
            {name : 'Browning, Gary'},
            {name : 'Bruce, Edward'},
            {name : 'Bryan, Nancy'},
            {name : 'Bryant, Tomas'},
            {name : 'Buchanan, Nancy'},
            {name : 'Buck, Krishna'},
            {name : 'Buckley, Kelly'},
            {name : 'Buckner, Ray'},
            {name : 'Bullock, Krishna'},
            {name : 'Burch, Helen'},
            {name : 'Burgess, Sharon'},
            {name : 'Burke, Edward'},
            {name : 'Burks, Sharon'},
            {name : 'Burnett, Tomas'},
            {name : 'Burns, Sharon'},
            {name : 'Burris, Sharon'},
            {name : 'Burt, Tomas'},
            {name : 'Burton, Nancy'},
            {name : 'Bush, Helen'},
            {name : 'Butler, Ray'},
            {name : 'Byers, Sharon'},
            {name : 'Byrd, David'},
            {name : 'Cabrera, Adam'},
            {name : 'Cain, Nancy'},
            {name : 'Calderon, Nancy'},
            {name : 'Caldwell, Larry'},
            {name : 'Calhoun, Nancy'},
            {name : 'Callahan, Nancy'},
            {name : 'Camacho, Oscar'},
            {name : 'Cameron, Nancy'},
            {name : 'Campbell, Larry'},
            {name : 'Campos, Sharon'},
            {name : 'Cannon, Nancy'},
            {name : 'Cantrell, Larry'},
            {name : 'Cantu, Ubuntu'},
            {name : 'Cardenas, Sharon'},
            {name : 'Carey, Kelly'},
            {name : 'Carlson, Nancy'},
            {name : 'Carney, Kelly'},
            {name : 'Carpenter, Ray'},
            {name : 'Carr, Ray'},
            {name : 'Carrillo, Oscar'},
            {name : 'Carroll, Larry'},
            {name : 'Carson, Nancy'},
            {name : 'Carter, Ray'},
            {name : 'Carver, Ray'},
            {name : 'Case, Edward'},
            {name : 'Casey, Kelly'},
            {name : 'Cash, Helen'},
            {name : 'Castaneda, Adam'},
            {name : 'Castillo, Oscar'},
            {name : 'Castro, Oscar'},
            {name : 'Cervantes, Sharon'},
            {name : 'Chambers, Sharon'},
            {name : 'Chan, Nancy'},
            {name : 'Chandler, Ray'},
            {name : 'Chaney, Kelly'},
            {name : 'Chang, Gary'},
            {name : 'Chapman, Nancy'},
            {name : 'Charles, Sharon'},
            {name : 'Chase, Edward'},
            {name : 'Chavez, Zorb'},
            {name : 'Chen, Nancy'},
            {name : 'Cherry, Kelly'},
            {name : 'Christensen, Nancy'},
            {name : 'Christian, Nancy'},
            {name : 'Church, Helen'},
            {name : 'Clark, Krishna'},
            {name : 'Clarke, Edward'},
            {name : 'Clay, Kelly'},
            {name : 'Clayton, Nancy'},
            {name : 'Clements, Sharon'},
            {name : 'Clemons, Sharon'},
            {name : 'Cleveland, David'},
            {name : 'Cline, Edward'},
            {name : 'Cobb, Barry'},
            {name : 'Cochran, Nancy'},
            {name : 'Coffey, Kelly'},
            {name : 'Cohen, Nancy'},
            {name : 'Cole, Edward'},
            {name : 'Coleman, Nancy'},
            {name : 'Collier, Ray'},
            {name : 'Collins, Sharon'},
            {name : 'Colon, Nancy'},
            {name : 'Combs, Sharon'},
            {name : 'Compton, Nancy'},
            {name : 'Conley, Kelly'},
            {name : 'Conner, Ray'},
            {name : 'Conrad, David'},
            {name : 'Contreras, Sharon'},
            {name : 'Conway, Kelly'},
            {name : 'Cook, Krishna'},
            {name : 'Cooke, Edward'},
            {name : 'Cooley, Kelly'},
            {name : 'Cooper, Ray'},
            {name : 'Copeland, David'},
            {name : 'Cortez, Zorb'},
            {name : 'Cote, Edward'},
            {name : 'Cotton, Nancy'},
            {name : 'Cox, Xander'},
            {name : 'Craft, Tomas'},
            {name : 'Craig, Gary'},
            {name : 'Crane, Edward'},
            {name : 'Crawford, David'},
            {name : 'Crosby, Kelly'},
            {name : 'Cross, Sharon'},
            {name : 'Cruz, Zorb'},
            {name : 'Cummings, Sharon'},
            {name : 'Cunningham, Michael'},
            {name : 'Curry, Kelly'},
            {name : 'Curtis, Sharon'},
            {name : 'Dale, Edward'},
            {name : 'Dalton, Nancy'},
            {name : 'Daniel, Larry'},
            {name : 'Daniels, Sharon'},
            {name : 'Daugherty, Kelly'},
            {name : 'Davenport, Tomas'},
            {name : 'David, David'},
            {name : 'Davidson, Nancy'},
            {name : 'Davis, Sharon'},
            {name : 'Dawson, Nancy'},
            {name : 'Day, Kelly'},
            {name : 'Dean, Nancy'},
            {name : 'Decker, Ray'},
            {name : 'Dejesus, Sharon'},
            {name : 'Delacruz, Zorb'},
            {name : 'Delaney, Kelly'},
            {name : 'Deleon, Nancy'},
            {name : 'Delgado, Oscar'},
            {name : 'Dennis, Sharon'},
            {name : 'Diaz, Zorb'},
            {name : 'Dickerson, Nancy'},
            {name : 'Dickson, Nancy'},
            {name : 'Dillard, David'},
            {name : 'Dillon, Nancy'},
            {name : 'Dixon, Nancy'},
            {name : 'Dodson, Nancy'},
            {name : 'Dominguez, Zorb'},
            {name : 'Donaldson, Nancy'},
            {name : 'Donovan, Nancy'},
            {name : 'Dorsey, Kelly'},
            {name : 'Dotson, Nancy'},
            {name : 'Douglas, Sharon'},
            {name : 'Downs, Sharon'},
            {name : 'Doyle, Edward'},
            {name : 'Drake, Edward'},
            {name : 'Dudley, Kelly'},
            {name : 'Duffy, Kelly'},
            {name : 'Duke, Edward'},
            {name : 'Duncan, Nancy'},
            {name : 'Dunlap, Paul'},
            {name : 'Dunn, Nancy'},
            {name : 'Duran, Nancy'},
            {name : 'Durham, Michael'},
            {name : 'Dyer, Ray'},
            {name : 'Eaton, Nancy'},
            {name : 'Edwards, Sharon'},
            {name : 'Elliott, Tomas'},
            {name : 'Ellis, Sharon'},
            {name : 'Ellison, Nancy'},
            {name : 'Emerson, Nancy'},
            {name : 'England, David'},
            {name : 'English, Helen'},
            {name : 'Erickson, Nancy'},
            {name : 'Espinoza, Adam'},
            {name : 'Estes, Sharon'},
            {name : 'Estrada, Adam'},
            {name : 'Evans, Sharon'},
            {name : 'Everett, Tomas'},
            {name : 'Ewing, Gary'},
            {name : 'Farley, Kelly'},
            {name : 'Farmer, Ray'},
            {name : 'Farrell, Larry'},
            {name : 'Faulkner, Ray'},
            {name : 'Ferguson, Nancy'},
            {name : 'Fernandez, Zorb'},
            {name : 'Ferrell, Larry'},
            {name : 'Fields, Sharon'},
            {name : 'Figueroa, Adam'},
            {name : 'Finch, Helen'},
            {name : 'Finley, Kelly'},
            {name : 'Fischer, Ray'},
            {name : 'Fisher, Ray'},
            {name : 'Fitzgerald, David'},
            {name : 'Fitzpatrick, Krishna'},
            {name : 'Fleming, Gary'},
            {name : 'Fletcher, Ray'},
            {name : 'Flores, Sharon'},
            {name : 'Flowers, Sharon'},
            {name : 'Floyd, David'},
            {name : 'Flynn, Nancy'},
            {name : 'Foley, Kelly'},
            {name : 'Forbes, Sharon'},
            {name : 'Ford, David'},
            {name : 'Foreman, Nancy'},
            {name : 'Foster, Ray'},
            {name : 'Fowler, Ray'},
            {name : 'Fox, Xander'},
            {name : 'Francis, Sharon'},
            {name : 'Franco, Oscar'},
            {name : 'Frank, Krishna'},
            {name : 'Franklin, Nancy'},
            {name : 'Franks, Sharon'},
            {name : 'Frazier, Ray'},
            {name : 'Frederick, Krishna'},
            {name : 'Freeman, Nancy'},
            {name : 'French, Helen'},
            {name : 'Frost, Tomas'},
            {name : 'Fry, Kelly'},
            {name : 'Frye, Edward'},
            {name : 'Fuentes, Sharon'},
            {name : 'Fuller, Ray'},
            {name : 'Fulton, Nancy'},
            {name : 'Gaines, Sharon'},
            {name : 'Gallagher, Ray'},
            {name : 'Gallegos, Sharon'},
            {name : 'Galloway, Kelly'},
            {name : 'Gamble, Edward'},
            {name : 'Garcia, Adam'},
            {name : 'Gardner, Ray'},
            {name : 'Garner, Ray'},
            {name : 'Garrett, Tomas'},
            {name : 'Garrison, Nancy'},
            {name : 'Garza, Adam'},
            {name : 'Gates, Sharon'},
            {name : 'Gay, Kelly'},
            {name : 'Gentry, Kelly'},
            {name : 'George, Edward'},
            {name : 'Gibbs, Sharon'},
            {name : 'Gibson, Nancy'},
            {name : 'Gilbert, Tomas'},
            {name : 'Giles, Sharon'},
            {name : 'Gill, Larry'},
            {name : 'Gillespie, Edward'},
            {name : 'Gilliam, Michael'},
            {name : 'Gilmore, Edward'},
            {name : 'Glass, Sharon'},
            {name : 'Glenn, Nancy'},
            {name : 'Glover, Ray'},
            {name : 'Goff, Frank'},
            {name : 'Golden, Nancy'},
            {name : 'Gomez, Zorb'},
            {name : 'Gonzales, Sharon'},
            {name : 'Gonzalez, Zorb'},
            {name : 'Good, David'},
            {name : 'Goodman, Nancy'},
            {name : 'Goodwin, Nancy'},
            {name : 'Gordon, Nancy'},
            {name : 'Gould, David'},
            {name : 'Graham, Michael'},
            {name : 'Grant, Tomas'},
            {name : 'Graves, Sharon'},
            {name : 'Gray, Kelly'},
            {name : 'Green, Nancy'},
            {name : 'Greene, Edward'},
            {name : 'Greer, Ray'},
            {name : 'Gregory, Kelly'},
            {name : 'Griffin, Nancy'},
            {name : 'Griffith, Helen'},
            {name : 'Grimes, Sharon'},
            {name : 'Gross, Sharon'},
            {name : 'Guerra, Adam'},
            {name : 'Guerrero, Oscar'},
            {name : 'Guthrie, Edward'},
            {name : 'Gutierrez, Zorb'},
            {name : 'Guy, Kelly'},
            {name : 'Guzman, Nancy'},
            {name : 'Hahn, Nancy'},
            {name : 'Hale, Edward'},
            {name : 'Haley, Kelly'},
            {name : 'Hall, Larry'},
            {name : 'Hamilton, Nancy'},
            {name : 'Hammond, David'},
            {name : 'Hampton, Nancy'},
            {name : 'Hancock, Krishna'},
            {name : 'Haney, Kelly'},
            {name : 'Hansen, Nancy'},
            {name : 'Hanson, Nancy'},
            {name : 'Hardin, Nancy'},
            {name : 'Harding, Gary'},
            {name : 'Hardy, Kelly'},
            {name : 'Harmon, Nancy'},
            {name : 'Harper, Ray'},
            {name : 'Harrell, Larry'},
            {name : 'Harrington, Nancy'},
            {name : 'Harris, Sharon'},
            {name : 'Harrison, Nancy'},
            {name : 'Hart, Tomas'},
            {name : 'Hartman, Nancy'},
            {name : 'Harvey, Kelly'},
            {name : 'Hatfield, David'},
            {name : 'Hawkins, Sharon'},
            {name : 'Hayden, Nancy'},
            {name : 'Hayes, Sharon'},
            {name : 'Haynes, Sharon'},
            {name : 'Hays, Sharon'},
            {name : 'Head, David'},
            {name : 'Heath, Helen'},
            {name : 'Hebert, Tomas'},
            {name : 'Henderson, Nancy'},
            {name : 'Hendricks, Sharon'},
            {name : 'Hendrix, Xander'},
            {name : 'Henry, Kelly'},
            {name : 'Hensley, Kelly'},
            {name : 'Henson, Nancy'},
            {name : 'Herman, Nancy'},
            {name : 'Hernandez, Zorb'},
            {name : 'Herrera, Adam'},
            {name : 'Herring, Gary'},
            {name : 'Hess, Sharon'},
            {name : 'Hester, Ray'},
            {name : 'Hewitt, Tomas'},
            {name : 'Hickman, Nancy'},
            {name : 'Hicks, Sharon'},
            {name : 'Higgins, Sharon'},
            {name : 'Hill, Larry'},
            {name : 'Hines, Sharon'},
            {name : 'Hinton, Nancy'},
            {name : 'Hobbs, Sharon'},
            {name : 'Hodge, Edward'},
            {name : 'Hodges, Sharon'},
            {name : 'Hoffman, Nancy'},
            {name : 'Hogan, Nancy'},
            {name : 'Holcomb, Barry'},
            {name : 'Holden, Nancy'},
            {name : 'Holder, Ray'},
            {name : 'Holland, David'},
            {name : 'Holloway, Kelly'},
            {name : 'Holman, Nancy'},
            {name : 'Holmes, Sharon'},
            {name : 'Holt, Tomas'},
            {name : 'Hood, David'},
            {name : 'Hooper, Ray'},
            {name : 'Hoover, Ray'},
            {name : 'Hopkins, Sharon'},
            {name : 'Hopper, Ray'},
            {name : 'Horn, Nancy'},
            {name : 'Horne, Edward'},
            {name : 'Horton, Nancy'},
            {name : 'House, Edward'},
            {name : 'Houston, Nancy'},
            {name : 'Howard, David'},
            {name : 'Howe, Edward'},
            {name : 'Howell, Larry'},
            {name : 'Hubbard, David'},
            {name : 'Huber, Ray'},
            {name : 'Hudson, Nancy'},
            {name : 'Huff, Frank'},
            {name : 'Huffman, Nancy'},
            {name : 'Hughes, Sharon'},
            {name : 'Hull, Larry'},
            {name : 'Humphrey, Kelly'},
            {name : 'Hunt, Tomas'},
            {name : 'Hunter, Ray'},
            {name : 'Hurley, Kelly'},
            {name : 'Hurst, Tomas'},
            {name : 'Hutchinson, Nancy'},
            {name : 'Hyde, Edward'},
            {name : 'Ingram, Michael'},
            {name : 'Irwin, Nancy'},
            {name : 'Jackson, Nancy'},
            {name : 'Jacobs, Sharon'},
            {name : 'Jacobson, Nancy'},
            {name : 'James, Sharon'},
            {name : 'Jarvis, Sharon'},
            {name : 'Jefferson, Nancy'},
            {name : 'Jenkins, Sharon'},
            {name : 'Jennings, Sharon'},
            {name : 'Jensen, Nancy'},
            {name : 'Jimenez, Zorb'},
            {name : 'Johns, Sharon'},
            {name : 'Johnson, Nancy'},
            {name : 'Johnston, Nancy'},
            {name : 'Jones, Sharon'},
            {name : 'Jordan, Nancy'},
            {name : 'Joseph, Helen'},
            {name : 'Joyce, Edward'},
            {name : 'Joyner, Ray'},
            {name : 'Juarez, Zorb'},
            {name : 'Justice, Edward'},
            {name : 'Kane, Edward'},
            {name : 'Kaufman, Nancy'},
            {name : 'Keith, Helen'},
            {name : 'Keller, Ray'},
            {name : 'Kelley, Kelly'},
            {name : 'Kelly, Kelly'},
            {name : 'Kemp, Paul'},
            {name : 'Kennedy, Kelly'},
            {name : 'Kent, Tomas'},
            {name : 'Kerr, Ray'},
            {name : 'Key, Kelly'},
            {name : 'Kidd, David'},
            {name : 'Kim, Michael'},
            {name : 'King, Gary'},
            {name : 'Kinney, Kelly'},
            {name : 'Kirby, Kelly'},
            {name : 'Kirk, Krishna'},
            {name : 'Kirkland, David'},
            {name : 'Klein, Nancy'},
            {name : 'Kline, Edward'},
            {name : 'Knapp, Paul'},
            {name : 'Knight, Tomas'},
            {name : 'Knowles, Sharon'},
            {name : 'Knox, Xander'},
            {name : 'Koch, Helen'},
            {name : 'Kramer, Ray'},
            {name : 'Lamb, Barry'},
            {name : 'Lambert, Tomas'},
            {name : 'Lancaster, Ray'},
            {name : 'Landry, Kelly'},
            {name : 'Lane, Edward'},
            {name : 'Lang, Gary'},
            {name : 'Langley, Kelly'},
            {name : 'Lara, Adam'},
            {name : 'Larsen, Nancy'},
            {name : 'Larson, Nancy'},
            {name : 'Lawrence, Edward'},
            {name : 'Lawson, Nancy'},
            {name : 'Le, Edward'},
            {name : 'Leach, Helen'},
            {name : 'Leblanc, Carl'},
            {name : 'Lee, Edward'},
            {name : 'Leon, Nancy'},
            {name : 'Leonard, David'},
            {name : 'Lester, Ray'},
            {name : 'Levine, Edward'},
            {name : 'Levy, Kelly'},
            {name : 'Lewis, Sharon'},
            {name : 'Lindsay, Kelly'},
            {name : 'Lindsey, Kelly'},
            {name : 'Little, Edward'},
            {name : 'Livingston, Nancy'},
            {name : 'Lloyd, David'},
            {name : 'Logan, Nancy'},
            {name : 'Long, Gary'},
            {name : 'Lopez, Zorb'},
            {name : 'Lott, Tomas'},
            {name : 'Love, Edward'},
            {name : 'Lowe, Edward'},
            {name : 'Lowery, Kelly'},
            {name : 'Lucas, Sharon'},
            {name : 'Luna, Adam'},
            {name : 'Lynch, Helen'},
            {name : 'Lynn, Nancy'},
            {name : 'Lyons, Sharon'},
            {name : 'Macdonald, David'},
            {name : 'Macias, Sharon'},
            {name : 'Mack, Krishna'},
            {name : 'Madden, Nancy'},
            {name : 'Maddox, Xander'},
            {name : 'Maldonado, Oscar'},
            {name : 'Malone, Edward'},
            {name : 'Mann, Nancy'},
            {name : 'Manning, Gary'},
            {name : 'Marks, Sharon'},
            {name : 'Marquez, Zorb'},
            {name : 'Marsh, Helen'},
            {name : 'Marshall, Larry'},
            {name : 'Martin, Nancy'},
            {name : 'Martinez, Zorb'},
            {name : 'Mason, Nancy'},
            {name : 'Massey, Kelly'},
            {name : 'Mathews, Sharon'},
            {name : 'Mathis, Sharon'},
            {name : 'Matthews, Sharon'},
            {name : 'Maxwell, Larry'},
            {name : 'May, Kelly'},
            {name : 'Mayer, Ray'},
            {name : 'Maynard, David'},
            {name : 'Mayo, Oscar'},
            {name : 'Mays, Sharon'},
            {name : 'Mcbride, Edward'},
            {name : 'Mccall, Larry'},
            {name : 'Mccarthy, Kelly'},
            {name : 'Mccarty, Kelly'},
            {name : 'Mcclain, Nancy'},
            {name : 'Mcclure, Edward'},
            {name : 'Mcconnell, Larry'},
            {name : 'Mccormick, Krishna'},
            {name : 'Mccoy, Kelly'},
            {name : 'Mccray, Kelly'},
            {name : 'Mccullough, Helen'},
            {name : 'Mcdaniel, Larry'},
            {name : 'Mcdonald, David'},
            {name : 'Mcdowell, Larry'},
            {name : 'Mcfadden, Nancy'},
            {name : 'Mcfarland, David'},
            {name : 'Mcgee, Edward'},
            {name : 'Mcgowan, Nancy'},
            {name : 'Mcguire, Edward'},
            {name : 'Mcintosh, Helen'},
            {name : 'Mcintyre, Edward'},
            {name : 'Mckay, Kelly'},
            {name : 'Mckee, Edward'},
            {name : 'Mckenzie, Edward'},
            {name : 'Mckinney, Kelly'},
            {name : 'Mcknight, Tomas'},
            {name : 'Mclaughlin, Nancy'},
            {name : 'Mclean, Nancy'},
            {name : 'Mcleod, David'},
            {name : 'Mcmahon, Nancy'},
            {name : 'Mcmillan, Nancy'},
            {name : 'Mcneil, Larry'},
            {name : 'Mcpherson, Nancy'},
            {name : 'Meadows, Sharon'},
            {name : 'Medina, Adam'},
            {name : 'Mejia, Adam'},
            {name : 'Melendez, Zorb'},
            {name : 'Melton, Nancy'},
            {name : 'Mendez, Zorb'},
            {name : 'Mendoza, Adam'},
            {name : 'Mercado, Oscar'},
            {name : 'Mercer, Ray'},
            {name : 'Merrill, Larry'},
            {name : 'Merritt, Tomas'},
            {name : 'Meyer, Ray'},
            {name : 'Meyers, Sharon'},
            {name : 'Michael, Larry'},
            {name : 'Middleton, Nancy'},
            {name : 'Miles, Sharon'},
            {name : 'Miller, Ray'},
            {name : 'Mills, Sharon'},
            {name : 'Miranda, Adam'},
            {name : 'Mitchell, Larry'},
            {name : 'Molina, Adam'},
            {name : 'Monroe, Edward'},
            {name : 'Montgomery, Kelly'},
            {name : 'Montoya, Adam'},
            {name : 'Moody, Kelly'},
            {name : 'Moon, Nancy'},
            {name : 'Mooney, Kelly'},
            {name : 'Moore, Edward'},
            {name : 'Morales, Sharon'},
            {name : 'Moran, Nancy'},
            {name : 'Moreno, Oscar'},
            {name : 'Morgan, Nancy'},
            {name : 'Morin, Nancy'},
            {name : 'Morris, Sharon'},
            {name : 'Morrison, Nancy'},
            {name : 'Morrow, Wilson'},
            {name : 'Morse, Edward'},
            {name : 'Morton, Nancy'},
            {name : 'Moses, Sharon'},
            {name : 'Mosley, Kelly'},
            {name : 'Moss, Sharon'},
            {name : 'Mueller, Ray'},
            {name : 'Mullen, Nancy'},
            {name : 'Mullins, Sharon'},
            {name : 'Munoz, Zorb'},
            {name : 'Murphy, Kelly'},
            {name : 'Murray, Kelly'},
            {name : 'Myers, Sharon'},
            {name : 'Nash, Helen'},
            {name : 'Navarro, Oscar'},
            {name : 'Neal, Larry'},
            {name : 'Nelson, Nancy'},
            {name : 'Newman, Nancy'},
            {name : 'Newton, Nancy'},
            {name : 'Nguyen, Nancy'},
            {name : 'Nichols, Sharon'},
            {name : 'Nicholson, Nancy'},
            {name : 'Nielsen, Nancy'},
            {name : 'Nieves, Sharon'},
            {name : 'Nixon, Nancy'},
            {name : 'Noble, Edward'},
            {name : 'Noel, Larry'},
            {name : 'Nolan, Nancy'},
            {name : 'Norman, Nancy'},
            {name : 'Norris, Sharon'},
            {name : 'Norton, Nancy'},
            {name : 'Nunez, Zorb'},
            {name : 'Obrien, Nancy'},
            {name : 'Ochoa, Adam'},
            {name : 'Oconnor, Ray'},
            {name : 'Odom, Michael'},
            {name : 'Odonnell, Larry'},
            {name : 'Oliver, Ray'},
            {name : 'Olsen, Nancy'},
            {name : 'Olson, Nancy'},
            {name : 'Oneal, Larry'},
            {name : 'Oneil, Larry'},
            {name : 'Oneill, Larry'},
            {name : 'Orr, Ray'},
            {name : 'Ortega, Adam'},
            {name : 'Ortiz, Zorb'},
            {name : 'Osborn, Nancy'},
            {name : 'Osborne, Edward'},
            {name : 'Owen, Nancy'},
            {name : 'Owens, Sharon'},
            {name : 'Pace, Edward'},
            {name : 'Pacheco, Oscar'},
            {name : 'Padilla, Adam'},
            {name : 'Page, Edward'},
            {name : 'Palmer, Ray'},
            {name : 'Park, Krishna'},
            {name : 'Parker, Ray'},
            {name : 'Parks, Sharon'},
            {name : 'Parrish, Helen'},
            {name : 'Parsons, Sharon'},
            {name : 'Pate, Edward'},
            {name : 'Patel, Larry'},
            {name : 'Patrick, Krishna'},
            {name : 'Patterson, Nancy'},
            {name : 'Patton, Nancy'},
            {name : 'Paul, Larry'},
            {name : 'Payne, Edward'},
            {name : 'Pearson, Nancy'},
            {name : 'Peck, Krishna'},
            {name : 'Pena, Adam'},
            {name : 'Pennington, Nancy'},
            {name : 'Perez, Zorb'},
            {name : 'Perkins, Sharon'},
            {name : 'Perry, Kelly'},
            {name : 'Peters, Sharon'},
            {name : 'Petersen, Nancy'},
            {name : 'Peterson, Nancy'},
            {name : 'Petty, Kelly'},
            {name : 'Phelps, Sharon'},
            {name : 'Phillips, Sharon'},
            {name : 'Pickett, Tomas'},
            {name : 'Pierce, Edward'},
            {name : 'Pittman, Nancy'},
            {name : 'Pitts, Sharon'},
            {name : 'Pollard, David'},
            {name : 'Poole, Edward'},
            {name : 'Pope, Edward'},
            {name : 'Porter, Ray'},
            {name : 'Potter, Ray'},
            {name : 'Potts, Sharon'},
            {name : 'Powell, Larry'},
            {name : 'Powers, Sharon'},
            {name : 'Pratt, Tomas'},
            {name : 'Preston, Nancy'},
            {name : 'Price, Edward'},
            {name : 'Prince, Edward'},
            {name : 'Pruitt, Tomas'},
            {name : 'Puckett, Tomas'},
            {name : 'Pugh, Helen'},
            {name : 'Quinn, Nancy'},
            {name : 'Ramirez, Zorb'},
            {name : 'Ramos, Sharon'},
            {name : 'Ramsey, Kelly'},
            {name : 'Randall, Larry'},
            {name : 'Randolph, Helen'},
            {name : 'Rasmussen, Nancy'},
            {name : 'Ratliff, Frank'},
            {name : 'Ray, Kelly'},
            {name : 'Raymond, David'},
            {name : 'Reed, David'},
            {name : 'Reese, Edward'},
            {name : 'Reeves, Sharon'},
            {name : 'Reid, David'},
            {name : 'Reilly, Kelly'},
            {name : 'Reyes, Sharon'},
            {name : 'Reynolds, Sharon'},
            {name : 'Rhodes, Sharon'},
            {name : 'Rice, Edward'},
            {name : 'Rich, Helen'},
            {name : 'Richard, David'},
            {name : 'Richards, Sharon'},
            {name : 'Richardson, Nancy'},
            {name : 'Richmond, David'},
            {name : 'Riddle, Edward'},
            {name : 'Riggs, Sharon'},
            {name : 'Riley, Kelly'},
            {name : 'Rios, Sharon'},
            {name : 'Rivas, Sharon'},
            {name : 'Rivera, Adam'},
            {name : 'Rivers, Sharon'},
            {name : 'Roach, Helen'},
            {name : 'Robbins, Sharon'},
            {name : 'Roberson, Nancy'},
            {name : 'Roberts, Sharon'},
            {name : 'Robertson, Nancy'},
            {name : 'Robinson, Nancy'},
            {name : 'Robles, Sharon'},
            {name : 'Rocha, Adam'},
            {name : 'Rodgers, Sharon'},
            {name : 'Rodriguez, Zorb'},
            {name : 'Rodriquez, Zorb'},
            {name : 'Rogers, Sharon'},
            {name : 'Rojas, Sharon'},
            {name : 'Rollins, Sharon'},
            {name : 'Roman, Nancy'},
            {name : 'Romero, Oscar'},
            {name : 'Rosa, Adam'},
            {name : 'Rosales, Sharon'},
            {name : 'Rosario, Oscar'},
            {name : 'Rose, Edward'},
            {name : 'Ross, Sharon'},
            {name : 'Roth, Helen'},
            {name : 'Rowe, Edward'},
            {name : 'Rowland, David'},
            {name : 'Roy, Kelly'},
            {name : 'Ruiz, Zorb'},
            {name : 'Rush, Helen'},
            {name : 'Russell, Larry'},
            {name : 'Russo, Oscar'},
            {name : 'Rutledge, Edward'},
            {name : 'Ryan, Nancy'},
            {name : 'Salas, Sharon'},
            {name : 'Salazar, Ray'},
            {name : 'Salinas, Sharon'},
            {name : 'Sampson, Nancy'},
            {name : 'Sanchez, Zorb'},
            {name : 'Sanders, Sharon'},
            {name : 'Sandoval, Larry'},
            {name : 'Sanford, David'},
            {name : 'Santana, Adam'},
            {name : 'Santiago, Oscar'},
            {name : 'Santos, Sharon'},
            {name : 'Sargent, Tomas'},
            {name : 'Saunders, Sharon'},
            {name : 'Savage, Edward'},
            {name : 'Sawyer, Ray'},
            {name : 'Schmidt, Tomas'},
            {name : 'Schneider, Ray'},
            {name : 'Schroeder, Ray'},
            {name : 'Schultz, Zorb'},
            {name : 'Schwartz, Zorb'},
            {name : 'Scott, Tomas'},
            {name : 'Sears, Sharon'},
            {name : 'Sellers, Sharon'},
            {name : 'Serrano, Oscar'},
            {name : 'Sexton, Nancy'},
            {name : 'Shaffer, Ray'},
            {name : 'Shannon, Nancy'},
            {name : 'Sharp, Paul'},
            {name : 'Sharpe, Edward'},
            {name : 'Shaw, Wilson'},
            {name : 'Shelton, Nancy'},
            {name : 'Shepard, David'},
            {name : 'Shepherd, David'},
            {name : 'Sheppard, David'},
            {name : 'Sherman, Nancy'},
            {name : 'Shields, Sharon'},
            {name : 'Short, Tomas'},
            {name : 'Silva, Adam'},
            {name : 'Simmons, Sharon'},
            {name : 'Simon, Nancy'},
            {name : 'Simpson, Nancy'},
            {name : 'Sims, Sharon'},
            {name : 'Singleton, Nancy'},
            {name : 'Skinner, Ray'},
            {name : 'Slater, Ray'},
            {name : 'Sloan, Nancy'},
            {name : 'Small, Larry'},
            {name : 'Smith, Helen'},
            {name : 'Snider, Ray'},
            {name : 'Snow, Wilson'},
            {name : 'Snyder, Ray'},
            {name : 'Solis, Sharon'},
            {name : 'Solomon, Nancy'},
            {name : 'Sosa, Adam'},
            {name : 'Soto, Oscar'},
            {name : 'Sparks, Sharon'},
            {name : 'Spears, Sharon'},
            {name : 'Spence, Edward'},
            {name : 'Spencer, Ray'},
            {name : 'Stafford, David'},
            {name : 'Stanley, Kelly'},
            {name : 'Stanton, Nancy'},
            {name : 'Stark, Krishna'},
            {name : 'Steele, Edward'},
            {name : 'Stein, Nancy'},
            {name : 'Stephens, Sharon'},
            {name : 'Stephenson, Nancy'},
            {name : 'Stevens, Sharon'},
            {name : 'Stevenson, Nancy'},
            {name : 'Stewart, Tomas'},
            {name : 'Stokes, Sharon'},
            {name : 'Stone, Edward'},
            {name : 'Stout, Tomas'},
            {name : 'Strickland, David'},
            {name : 'Strong, Gary'},
            {name : 'Stuart, Tomas'},
            {name : 'Suarez, Zorb'},
            {name : 'Sullivan, Nancy'},
            {name : 'Summers, Sharon'},
            {name : 'Sutton, Nancy'},
            {name : 'Swanson, Nancy'},
            {name : 'Sweeney, Kelly'},
            {name : 'Sweet, Tomas'},
            {name : 'Sykes, Sharon'},
            {name : 'Talley, Kelly'},
            {name : 'Tanner, Ray'},
            {name : 'Tate, Edward'},
            {name : 'Taylor, Ray'},
            {name : 'Terrell, Larry'},
            {name : 'Terry, Kelly'},
            {name : 'Thomas, Sharon'},
            {name : 'Thompson, Nancy'},
            {name : 'Thornton, Nancy'},
            {name : 'Tillman, Nancy'},
            {name : 'Todd, David'},
            {name : 'Torres, Sharon'},
            {name : 'Townsend, David'},
            {name : 'Tran, Nancy'},
            {name : 'Travis, Sharon'},
            {name : 'Trevino, Oscar'},
            {name : 'Trujillo, Oscar'},
            {name : 'Tucker, Ray'},
            {name : 'Turner, Ray'},
            {name : 'Tyler, Ray'},
            {name : 'Tyson, Nancy'},
            {name : 'Underwood, David'},
            {name : 'Valdez, Zorb'},
            {name : 'Valencia, Adam'},
            {name : 'Valentine, Edward'},
            {name : 'Valenzuela, Adam'},
            {name : 'Vance, Edward'},
            {name : 'Vang, Gary'},
            {name : 'Vargas, Sharon'},
            {name : 'Vasquez, Zorb'},
            {name : 'Vaughan, Nancy'},
            {name : 'Vaughn, Nancy'},
            {name : 'Vazquez, Zorb'},
            {name : 'Vega, Adam'},
            {name : 'Velasquez, Zorb'},
            {name : 'Velazquez, Zorb'},
            {name : 'Velez, Zorb'},
            {name : 'Villarreal, Larry'},
            {name : 'Vincent, Tomas'},
            {name : 'Vinson, Nancy'},
            {name : 'Wade, Edward'},
            {name : 'Wagner, Ray'},
            {name : 'Walker, Ray'},
            {name : 'Wall, Larry'},
            {name : 'Wallace, Edward'},
            {name : 'Waller, Ray'},
            {name : 'Walls, Sharon'},
            {name : 'Walsh, Helen'},
            {name : 'Walter, Ray'},
            {name : 'Walters, Sharon'},
            {name : 'Walton, Nancy'},
            {name : 'Ward, David'},
            {name : 'Ware, Edward'},
            {name : 'Warner, Ray'},
            {name : 'Warren, Nancy'},
            {name : 'Washington, Nancy'},
            {name : 'Waters, Sharon'},
            {name : 'Watkins, Sharon'},
            {name : 'Watson, Nancy'},
            {name : 'Watts, Sharon'},
            {name : 'Weaver, Ray'},
            {name : 'Webb, Barry'},
            {name : 'Weber, Ray'},
            {name : 'Webster, Ray'},
            {name : 'Weeks, Sharon'},
            {name : 'Weiss, Sharon'},
            {name : 'Welch, Helen'},
            {name : 'Wells, Sharon'},
            {name : 'West, Tomas'},
            {name : 'Wheeler, Ray'},
            {name : 'Whitaker, Ray'},
            {name : 'White, Edward'},
            {name : 'Whitehead, David'},
            {name : 'Whitfield, David'},
            {name : 'Whitley, Kelly'},
            {name : 'Whitney, Kelly'},
            {name : 'Wiggins, Sharon'},
            {name : 'Wilcox, Xander'},
            {name : 'Wilder, Ray'},
            {name : 'Wiley, Kelly'},
            {name : 'Wilkerson, Nancy'},
            {name : 'Wilkins, Sharon'},
            {name : 'Wilkinson, Nancy'},
            {name : 'William, Michael'},
            {name : 'Williams, Sharon'},
            {name : 'Williamson, Nancy'},
            {name : 'Willis, Sharon'},
            {name : 'Wilson, Nancy'},
            {name : 'Winters, Sharon'},
            {name : 'Wise, Edward'},
            {name : 'Witt, Tomas'},
            {name : 'Wolf, Frank'},
            {name : 'Wolfe, Edward'},
            {name : 'Wong, Gary'},
            {name : 'Wood, David'},
            {name : 'Woodard, David'},
            {name : 'Woods, Sharon'},
            {name : 'Woodward, David'},
            {name : 'Wooten, Nancy'},
            {name : 'Workman, Nancy'},
            {name : 'Wright, Tomas'},
            {name : 'Wyatt, Tomas'},
            {name : 'Wynn, Nancy'},
            {name : 'Yang, Gary'},
            {name : 'Yates, Sharon'},
            {name : 'York, Krishna'},
            {name : 'Young, Gary'},
            {name : 'Zamora, Adam'},
            {name : 'Zimmerman, Andy'}]
    });
});

router.get('/', function(req, res, next) {
    res.send('Choose parameters: /objects /strings')
})

module.exports = router;
